### ISSUE TITLE
no sound for open/close tab actions

### ISSUE THREAD

**Issue by oluc** [bootleq/Noise#6]
noise 1.4.2
Firefox 44.0.2
ubuntu 15.10

there is no sound for no action

In the "Noise Edit" window, you can play the sound: 
    Preferences> Edit> Play 
    --> sound ok

In the "Noise Preference" window, you hear no sound: 
     [select row]> Play 
     --> no sound

In firefox, for whatever action, you hear no sound, not even default beep: 
     --> no sound

**Comment by oluc** [comment]
hmm, ok, I missed the "Enable Sounds" checkbox.
Now works for open/close windows (at least).

still no sound for open/close tabs

**Comment by bootleq** [comment]
What's the setting for Tab open/close event?
A working example is:
Event: `TabOpen`
Event Type: `Window event (via window.addEventListener)`

**Comment by oluc** [comment]
I have
`Event: TabOpen`
`Event Type: Browser event (via gBrowser.addEventListener)`

OK, changing the later to...
   `Event Type: Window event (via window.addEventListener)`
... make it work.

It would be nice if the UI would be more talkative/obvious about the various settings.

Though, this closes the issue.
Thanks!
